# Generated by Django 3.2 on 2021-11-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='principio_activo',
            field=models.CharField(default='----', max_length=100),
        ),
    ]
